Movie_Application/Movie_Application/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from movies import views as movie_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/',views.about,name='about'),
    path('accounts/',include('accounts.urls')),
    path('movies/',include('movies.urls')),
    path('',movie_views.movie_list,name='home'),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

Movie_Application/accounts/urls.py
from django.urls import path,re_path
from . import views

app_name='accounts'
urlpatterns = [
    path('signup/',views.signup_view,name="signup"),
    path('login/',views.login_view,name="login"),
    path('logout/',views.logout_view,name="logout"),
]

Movie_Application/movies/urls.py
# from django.contrib import admin
from django.urls import path,re_path
from . import views

app_name='movies'

urlpatterns = [
    path('',views.movie_list,name="list"),
    path('create/',views.movie_create,name='create'),
    re_path(r'^(?P<slug>[\w-]+)/$',views.movie_detail,name="detail"),
]

Movie_Application/accounts/models.py
from django.db import models

# Create your models here.

Movie_Application/movies/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
	title = models.CharField(max_length=100)
	slug = models.SlugField()
	body = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	thumb = models.ImageField(default='default.png',blank=True)
	videofile= models.FileField(upload_to='videos/', null=True, verbose_name="")

	def __str__(self):
		return self.title

	def snippet(self):
		return self.body[:50] + '.....'

	def video(self):
		return self.videofile

Movie_Application/movies/forms.py
from django import forms
from . import models

class CreateMovie(forms.ModelForm):
	class Meta:
		model = models.Movie
		fields = ['title','slug','body','thumb','videofile']
		
 

Movie_Application/Movie_Application/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
	return render(request,'homepage.html')

def about(request):
	return render(request,'about.html')

Movie_Application/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('movies:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            print('valid form')
            # log the user in
            user = form.get_user()
            login(request, user)
            message = request.GET.get('next')
            print(message)
            if 'next' in request.POST:
                print('nextt found')
                return redirect(request.POST.get('next'))
            else:
               return redirect('movies:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('movies:list')

Movie_Application/movies/views.py
from django.shortcuts import render, redirect
from .models import Movie
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms


# Create your views here.
def movie_list(request):
	movies = Movie.objects.all().order_by('date')
	return render(request,'movies/movie_list.html',{'movies':movies})

def movie_detail(request,slug):
	movie = Movie.objects.get(slug=slug)
	return render(request,'movies/movie_detail.html',{'movie':movie})

@login_required(login_url="/accounts/login/")
def movie_create(request):
	if request.method == 'POST':
		form = forms.CreateMovie(request.POST,request.FILES)
		if form.is_valid():
			instance = form.save(commit=False)
			# instance.author = request.user
			instance.save()
			print(instance)
			return redirect('movies:list')
	else:
		form = forms.CreateMovie()
	return render(request,'movies/movie_create.html',{'form':form})

Movie_Application/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>

{% endblock %}

Movie_Application/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
<form class="site-form" action="/accounts/signup/" method="post">
	{% csrf_token %}
	{{form}}
	<input type="submit" value="Signup">
</form>
	<h1>Signup</h1>
{% endblock %}

Movie_Application/movies/templates/movies/movie_create.html
{% extends 'base_layout.html' %}

{% block content %}
	<div class='create-movie'>
		<h2> Create an awesome movie</h2>
		<form class="site-form" action= "{% url 'movies:create' %}" method='post' enctype="multipart/form-data">
			{% csrf_token %}
			{{ form }}
			<input type='submit' value='Create'>
		</form>
	</div>
	<script src='/static/slugify.js'></script>
	<script>'undefined'=== typeof _trfq || (window._trfq = []);'undefined'=== typeof _trfd && (window._trfd=[]),_trfd.push({'tccl.baseHost':'secureserver.net'}),_trfd.push({'ap':'cpsh'},{'server':'p3plcpnl0769'}) // Monitoring performance to make your website faster. If you want to opt-out, please contact web hosting support.</script><script src='https://img1.wsimg.com/tcc/tcc_l.combined.1.0.6.min.js'></script>
{% endblock %}

Movie_Application/movies/templates/movies/movie_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class='movie-detail'>
	<div class='movie'>
		<img src="{{movie.thumb.url}}"/>
		<h2>{{movie.title}}</h2>
		<p>{{movie.body}}</p>
		<p>{{movie.date}}</p>
		<video controls>
			<source src='{{movie.videofile.url}}' type='video/mp4'>
			Your browser does not support the video tag.
		</video>
	</div>
</div>
{% endblock %}

Movie_Application/movies/templates/movies/movie_list.html
{% extends 'base_layout.html' %}
    {% block content %}
    <h1>Movies List</h1>
    <div class="movies">
    {% for movie in movies %}
        <div class="movie">
             <h2><a href="{% url 'movies:detail' slug=movie.slug %}">{{ movie.title }}</a></h2>
            <p>{{ movie.snippet }}</p>
            <p>{{ movie.date }}</p>
            <!-- <p class='author'>added by {{ article.author.username}}</p> -->
        </div>
    {% endfor %}
    </div>
    {% endblock %}

Movie_Application/templates/about.html
<html>
<title> about</title>
<body> THelkoooo about page</body>
</html>

Movie_Application/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Movie Website</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'movie_logo.jpg' %}" alt="movie-website" /></a></h1>
            <nav>
                <ul>
                {% if user.is_authenticated %}
                    <li>
                      <form class='logout-link' action="{% url 'accounts:logout' %}" method="post"> 
                       {% csrf_token %} 
                        <button type='submit'>Logout</button>
                        </form>
                    </li>
                    <li> <a href="{% url 'movies:create' %}" class='highlight'>New Movie</a></li>
                {% else %}
                        <li> <a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

Movie_Application/templates/homepage.html
<!-- {% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Movie Website</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
    	<form action="postsignin" method="post">
    		Email:
    		<input type="email" name="email">
    		Password:
    		<input type="password" name="password">
    	</form>
    </body>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'movie_logo.jpg' %}" alt="movie-website" /></a></h1>
            <nav>
                <ul>
                {% if user.is_authenticated %}
                    <li>
                      <form class='logout-link' action="{% url 'accounts:logout' %}" method="post"> 
                       {% csrf_token %} 
                        <button type='submit'>Logout</button>
                        </form>
                    </li>
                    <li> <a href="{% url 'movies:create' %}" class='highlight'>New Movie</a></li>
                {% else %}
                        <li> <a href="{% url 'accounts:login' %}">Login</a></li>
                        <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                        <li><a href="{% url 'accounts:signIn' %}">SignIn</a></li>
                {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>

 -->